# Generated by Django 6.0.5 on 2026-05-15 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
