# Generated by Django 6.0.5 on 2026-05-15 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBApp', '0002_alter_invoice_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
