# Generated by Django 6.0.5 on 2026-05-15 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DBApp', '0003_invoice_paid_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='closing_balance',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='current_total',
        ),
    ]
