# Generated by Django 6.0.5 on 2026-05-15 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBApp', '0004_remove_invoice_closing_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='closing_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
