# Generated by Django 6.0.5 on 2026-05-21 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DBApp', '0007_invoice_pdf_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='pdf_file',
        ),
    ]
